#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : luv
Version  : 1.43.0.0
Release  : 4
URL      : https://github.com/luvit/luv/releases/download/1.43.0-0/luv-1.43.0-0.tar.gz
Source0  : https://github.com/luvit/luv/releases/download/1.43.0-0/luv-1.43.0-0.tar.gz
Summary  : Bare and full libuv bindings for Lua/LuaJIT.
Group    : Development/Tools
License  : Apache-2.0 CC-BY-4.0 MIT
Requires: luv-lib = %{version}-%{release}
Requires: luv-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : libuv-dev
BuildRequires : pkgconfig(luajit)

%description
luv
===
[![Linux Build Status](https://github.com/luvit/luv/actions/workflows/ci.yml/badge.svg)](https://github.com/luvit/luv/actions/workflows/ci.yml)
[![Windows Build status](https://ci.appveyor.com/api/projects/status/uo1qhdcc0vcqsiok/branch/master?svg=true)](https://ci.appveyor.com/project/racker-buildbot/luv/branch/master)
[![Code Quality: Cpp](https://img.shields.io/lgtm/grade/cpp/g/luvit/luv.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/luvit/luv/context:cpp)
[![Total Alerts](https://img.shields.io/lgtm/alerts/g/luvit/luv.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/luvit/luv/alerts)

%package dev
Summary: dev components for the luv package.
Group: Development
Requires: luv-lib = %{version}-%{release}
Provides: luv-devel = %{version}-%{release}
Requires: luv = %{version}-%{release}

%description dev
dev components for the luv package.


%package lib
Summary: lib components for the luv package.
Group: Libraries
Requires: luv-license = %{version}-%{release}

%description lib
lib components for the luv package.


%package license
Summary: license components for the luv package.
Group: Default

%description license
license components for the luv package.


%prep
%setup -q -n luv-1.43.0-0
cd %{_builddir}/luv-1.43.0-0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1650318619
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake .. -DLUA_BUILD_TYPE=System \
-DWITH_LUA_ENGINE=lua \
-DWITH_SHARED_LIBUV=ON \
-DBUILD_SHARED_LIBS=ON \
-DBUILD_MODULE=OFF \
-DSHAREDLIBS_INSTALL_LIB_DIR=/usr/lib64
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1650318619
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/luv
cp %{_builddir}/luv-1.43.0-0/LICENSE.txt %{buildroot}/usr/share/package-licenses/luv/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/luv-1.43.0-0/deps/libuv/LICENSE %{buildroot}/usr/share/package-licenses/luv/848f7398f89046426a7ba23cb56cd3c93c030c64
cp %{_builddir}/luv-1.43.0-0/deps/libuv/LICENSE-docs %{buildroot}/usr/share/package-licenses/luv/1167f0e28fe2db01e38e883aaf1e749fb09f9ceb
cp %{_builddir}/luv-1.43.0-0/deps/lua-compat-5.3/LICENSE %{buildroot}/usr/share/package-licenses/luv/94aa349711a3c990bd6f020ff5e1e2193708484f
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/luv/lhandle.h
/usr/include/luv/lreq.h
/usr/include/luv/luv.h
/usr/include/luv/util.h
/usr/lib64/libluv.so
/usr/lib64/pkgconfig/libluv.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libluv.so.1
/usr/lib64/libluv.so.1.43.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/luv/1167f0e28fe2db01e38e883aaf1e749fb09f9ceb
/usr/share/package-licenses/luv/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/luv/848f7398f89046426a7ba23cb56cd3c93c030c64
/usr/share/package-licenses/luv/94aa349711a3c990bd6f020ff5e1e2193708484f
