#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : luv
Version  : 1.30.1.1
Release  : 1
URL      : https://github.com/luvit/luv/archive/1.30.1-1.tar.gz
Source0  : https://github.com/luvit/luv/archive/1.30.1-1.tar.gz
Source1  : https://github.com/keplerproject/lua-compat-5.3/archive/v0.7.tar.gz
Summary  : Bare and full libuv bindings for Lua/LuaJIT.
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: luv-lib = %{version}-%{release}
Requires: luv-license = %{version}-%{release}
BuildRequires : LuaJIT-dev
BuildRequires : buildreq-cmake
BuildRequires : libuv-dev

%description
luv
===
[![Linux Build Status](https://travis-ci.org/luvit/luv.svg?branch=master)](https://travis-ci.org/luvit/luv)
[![Windows Build status](https://ci.appveyor.com/api/projects/status/uo1qhdcc0vcqsiok/branch/master?svg=true)](https://ci.appveyor.com/project/racker-buildbot/luv/branch/master)
[![Code Quality: Cpp](https://img.shields.io/lgtm/grade/cpp/g/luvit/luv.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/luvit/luv/context:cpp)
[![Total Alerts](https://img.shields.io/lgtm/alerts/g/luvit/luv.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/luvit/luv/alerts)

%package dev
Summary: dev components for the luv package.
Group: Development
Requires: luv-lib = %{version}-%{release}
Provides: luv-devel = %{version}-%{release}
Requires: luv = %{version}-%{release}

%description dev
dev components for the luv package.


%package lib
Summary: lib components for the luv package.
Group: Libraries
Requires: luv-license = %{version}-%{release}

%description lib
lib components for the luv package.


%package license
Summary: license components for the luv package.
Group: Default

%description license
license components for the luv package.


%prep
%setup -q -n luv-1.30.1-1
cd ..
%setup -q -T -D -n luv-1.30.1-1 -b 1
mkdir -p deps/lua-compat-5.3
cp -r %{_topdir}/BUILD/lua-compat-5.3-0.7/* %{_topdir}/BUILD/luv-1.30.1-1/deps/lua-compat-5.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571241866
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake .. -DWITH_SHARED_LIBUV=ON -DLUA_BUILD_TYPE=System -DBUILD_MODULE=OFF -DBUILD_SHARED_LIBS=ON -DLUA_COMPAT53_DIR=deps/lua-compat-5.3/ -DINSTALL_LIB_DIR=/usr/lib64
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1571241866
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/luv
cp %{_builddir}/luv-1.30.1-1/LICENSE.txt %{buildroot}/usr/share/package-licenses/luv/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/luv-1.30.1-1/deps/lua-compat-5.3/LICENSE %{buildroot}/usr/share/package-licenses/luv/94aa349711a3c990bd6f020ff5e1e2193708484f
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/luv/lhandle.h
/usr/include/luv/lreq.h
/usr/include/luv/luv.h
/usr/include/luv/util.h
/usr/lib64/libluv.so
/usr/lib64/pkgconfig/libluv.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libluv.so.1
/usr/lib64/libluv.so.1.30.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/luv/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/luv/94aa349711a3c990bd6f020ff5e1e2193708484f
