#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v16
# autospec commit: b858a2a
#
Name     : luv
Version  : 1.48.0.2
Release  : 7
URL      : https://github.com/luvit/luv/releases/download/1.48.0-2/luv-1.48.0-2.tar.gz
Source0  : https://github.com/luvit/luv/releases/download/1.48.0-2/luv-1.48.0-2.tar.gz
Summary  : Bare and full libuv bindings for Lua/LuaJIT.
Group    : Development/Tools
License  : Apache-2.0 CC-BY-4.0 MIT
Requires: luv-lib = %{version}-%{release}
Requires: luv-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : curl-dev
BuildRequires : libuv-dev
BuildRequires : pkgconfig(luajit)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
luv
===
[![Linux Build Status](https://github.com/luvit/luv/actions/workflows/ci.yml/badge.svg)](https://github.com/luvit/luv/actions/workflows/ci.yml)
[![Windows Build status](https://ci.appveyor.com/api/projects/status/uo1qhdcc0vcqsiok/branch/master?svg=true)](https://ci.appveyor.com/project/racker-buildbot/luv/branch/master)

%package dev
Summary: dev components for the luv package.
Group: Development
Requires: luv-lib = %{version}-%{release}
Provides: luv-devel = %{version}-%{release}
Requires: luv = %{version}-%{release}

%description dev
dev components for the luv package.


%package lib
Summary: lib components for the luv package.
Group: Libraries
Requires: luv-license = %{version}-%{release}

%description lib
lib components for the luv package.


%package license
Summary: license components for the luv package.
Group: Default

%description license
license components for the luv package.


%prep
%setup -q -n luv-1.48.0-2
cd %{_builddir}/luv-1.48.0-2
pushd ..
cp -a luv-1.48.0-2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720538826
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DLUA_BUILD_TYPE=System \
-DWITH_LUA_ENGINE=lua \
-DWITH_SHARED_LIBUV=ON \
-DBUILD_SHARED_LIBS=ON \
-DBUILD_MODULE=OFF \
-DSHAREDLIBS_INSTALL_LIB_DIR=/usr/lib64  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DLUA_BUILD_TYPE=System \
-DWITH_LUA_ENGINE=lua \
-DWITH_SHARED_LIBUV=ON \
-DBUILD_SHARED_LIBS=ON \
-DBUILD_MODULE=OFF \
-DSHAREDLIBS_INSTALL_LIB_DIR=/usr/lib64  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1720538826
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/luv
cp %{_builddir}/luv-1.48.0-2/LICENSE.txt %{buildroot}/usr/share/package-licenses/luv/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/luv-1.48.0-2/deps/libuv/LICENSE %{buildroot}/usr/share/package-licenses/luv/0b475e38bd94d37bcfbfc28ea7fc024bd80a280a || :
cp %{_builddir}/luv-1.48.0-2/deps/libuv/LICENSE-docs %{buildroot}/usr/share/package-licenses/luv/1167f0e28fe2db01e38e883aaf1e749fb09f9ceb || :
cp %{_builddir}/luv-1.48.0-2/deps/libuv/LICENSE-extra %{buildroot}/usr/share/package-licenses/luv/7db2a53252ca3d44462e8b3c050c97742d726850 || :
cp %{_builddir}/luv-1.48.0-2/deps/lua-compat-5.3/LICENSE %{buildroot}/usr/share/package-licenses/luv/07498ae13ffcf45cfc853622fed3000ae2ef9245 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
## install_append content
rm %{buildroot}/usr/lib64/pkgconfig/libluv.pc
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/luv/lhandle.h
/usr/include/luv/lreq.h
/usr/include/luv/luv.h
/usr/include/luv/util.h
/usr/lib64/libluv.so

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libluv.so.1.48.0
/usr/lib64/libluv.so.1
/usr/lib64/libluv.so.1.48.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/luv/07498ae13ffcf45cfc853622fed3000ae2ef9245
/usr/share/package-licenses/luv/0b475e38bd94d37bcfbfc28ea7fc024bd80a280a
/usr/share/package-licenses/luv/1167f0e28fe2db01e38e883aaf1e749fb09f9ceb
/usr/share/package-licenses/luv/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/luv/7db2a53252ca3d44462e8b3c050c97742d726850
